class_name Enemies
extends RefCounted

## combat.ts が import する getEnemy() のため、enemies.ts のカタログ＋getEnemy を最小移植。

const ENEMIES := {
	"acolyte": {
		"id": "acolyte",
		"name": "侍祭",
		"art": "res://art/pixel/acolyte.png",
		"poster": "res://art/pixel/acolyte.png",
		"biome": "shrine",
		"maxHp": 32,
		"archetype": "fanatic",
	},
	"fanatic": {
		"id": "fanatic",
		"name": "狂信者",
		"art": "res://art/pixel/fanatic.png",
		"poster": "res://art/pixel/fanatic.png",
		"biome": "shrine",
		"maxHp": 42,
		"tier": "elite",
		"archetype": "fanatic",
	},
	"drowned": {
		"id": "drowned",
		"name": "溺れた眷属",
		"art": "res://art/pixel/drowned.png",
		"poster": "res://art/pixel/drowned.png",
		"biome": "reef",
		"maxHp": 44,
		"archetype": "poison",
	},
	"byakhee": {
		"id": "byakhee",
		"name": "翼ある飢え",
		"art": "res://art/pixel/byakhee.png",
		"poster": "res://art/pixel/byakhee.png",
		"biome": "void",
		"maxHp": 38,
		"tier": "elite",
		"archetype": "outer",
		"floats": true,
	},
	"coral": {
		"id": "coral",
		"name": "礁の衛士",
		"art": "res://art/pixel/coral.png",
		"poster": "res://art/pixel/coral.png",
		"biome": "reef",
		"maxHp": 48,
		"tier": "elite",
		"archetype": "knight",
	},
	"starveling": {
		"id": "starveling",
		"name": "飢えし仔",
		"art": "res://art/pixel/starveling.png",
		"poster": "res://art/pixel/starveling.png",
		"biome": "reef",
		"maxHp": 86,
		"tier": "elite",
		"archetype": "water",
	},
	"serpent": {
		"id": "serpent",
		"name": "ムーの蛇人",
		"art": "res://art/pixel/serpent.png",
		"poster": "res://art/pixel/serpent.png",
		"biome": "mu",
		"maxHp": 54,
		"archetype": "water",
	},
	"spawn": {
		"id": "spawn",
		"name": "ガタノトアの落とし子",
		"art": "res://art/pixel/spawn.png",
		"poster": "res://art/pixel/spawn.png",
		"biome": "mu",
		"maxHp": 62,
		"archetype": "outer",
	},
	"migo": {
		"id": "migo",
		"name": "ミーゴ",
		"art": "res://art/pixel/migo.png",
		"poster": "res://art/pixel/migo.png",
		"biome": "void",
		"maxHp": 40,
		"archetype": "outer",
		"floats": true,
	},
	"colour": {
		"id": "colour",
		"name": "星から来た色",
		"art": "res://art/pixel/colour.png",
		"poster": "res://art/pixel/colour.png",
		"biome": "colour",
		"maxHp": 48,
		"archetype": "outer",
	},
	"starvamp": {
		"id": "starvamp",
		"name": "星の吸血獣",
		"art": "res://art/pixel/starvamp.png",
		"poster": "res://art/pixel/starvamp.png",
		"biome": "void",
		"maxHp": 56,
		"tier": "elite",
		"archetype": "outer",
		"floats": true,
	},
	"shan": {
		"id": "shan",
		"name": "シャガイの昆虫",
		"art": "res://art/pixel/shan.png",
		"poster": "res://art/pixel/shan.png",
		"biome": "void",
		"maxHp": 36,
		"archetype": "outer",
		"floats": true,
	},
	"priest": {
		"id": "priest",
		"name": "尖塔の大司祭",
		"art": "res://art/pixel/priest.png",
		"poster": "res://art/pixel/priest.png",
		"biome": "shrine",
		"maxHp": 168,
		"archetype": "fanatic",
		"signatureCardId": "revelation",
		"cardsPerTurn": 2,
		"deck": ["revelation", "lash", "bash", "ward", "chant"],
	},
	"choir": {
		"id": "choir",
		"name": "塩の唱者",
		"art": "res://art/pixel/choir.png",
		"poster": "res://art/pixel/choir.png",
		"biome": "street",
		"maxHp": 42,
		"trait": "choir",
		"archetype": "shadow",
		"signatureCardId": "chorusunity",
		"cardsPerTurn": 2,
		"deck": ["chorusunity", "strike", "sigil", "rite"],
	},
	"nurse": {
		"id": "nurse",
		"name": "深きものの乳母",
		"art": "res://art/pixel/nurse.png",
		"poster": "res://art/pixel/nurse.png",
		"biome": "reef",
		"maxHp": 112,
		"trait": "nurse",
		"archetype": "poison",
		"signatureCardId": "embrace",
		"cardsPerTurn": 2,
		"deck": ["embrace", "dressing", "bash", "all-vacuum"],
	},
	"flock": {
		"id": "flock",
		"name": "飢えた翼",
		"art": "res://art/pixel/flock.png",
		"poster": "res://art/pixel/flock.png",
		"biome": "reef",
		"maxHp": 52,
		"archetype": "water",
		"floats": true,
		"signatureCardId": "flockrush",
		"cardsPerTurn": 2,
		"deck": ["flockrush", "lash", "all-glass", "ward"],
	},
	"warden": {
		"id": "warden",
		"name": "曲がる幾何の番",
		"art": "res://art/pixel/warden.png",
		"poster": "res://art/pixel/warden.png",
		"biome": "fold",
		"maxHp": 108,
		"trait": "liar",
		"archetype": "knight",
		"signatureCardId": "noneuclid",
		"cardsPerTurn": 2,
		"deck": ["noneuclid", "eldersign", "all-phase", "bash", "all-geo"],
	},
	"bell": {
		"id": "bell",
		"name": "溺れた街の鐘",
		"art": "res://art/pixel/bell.png",
		"poster": "res://art/pixel/bell.png",
		"biome": "street",
		"maxHp": 118,
		"trait": "bell",
		"archetype": "shadow",
		"signatureCardId": "tollbell",
		"cardsPerTurn": 2,
		"deck": ["tollbell", "all-necrosis", "all-zero", "ironwill"],
	},
	"nyar": {
		"id": "nyar",
		"name": "門番ナイアルラト",
		"art": "res://art/pixel/nyar.png",
		"poster": "res://art/pixel/nyar.png",
		"biome": "throne",
		"maxHp": 124,
		"archetype": "shadow",
		"signatureCardId": "pricewisdom",
		"cardsPerTurn": 2,
		"deck": ["pricewisdom", "all-necrosis", "rite", "all-vacuum", "eldersign", "evil_eye_bind", "silent_bind"],
	},
	"iha": {
		"id": "iha",
		"name": "緑の腐肉、イハ",
		"art": "res://art/pixel/iha.png",
		"poster": "res://art/pixel/iha.png",
		"biome": "throne",
		"maxHp": 96,
		"trait": "split",
		"archetype": "greatold",
		"signatureCardId": "protosurge",
		"cardsPerTurn": 2,
		"deck": ["protosurge", "all-geo", "all-glass", "ironwill", "all-zero"],
	},
	"herald": {
		"id": "herald",
		"name": "呼び声の使徒",
		"art": "res://art/pixel/herald.png",
		"poster": "res://art/pixel/herald.png",
		"biome": "throne",
		"maxHp": 214,
		"archetype": "offering",
		"signatureCardId": "heraldscall",
		"cardsPerTurn": 2,
		"deck": ["heraldscall", "thecall", "all-zero", "ironwill", "eldersign"],
	},
	"yog_sothoth": {
		"id": "yog_sothoth",
		"name": "全なる者",
		"art": "res://art/pixel/yog_sothoth.png",
		"poster": "res://art/pixel/yog_sothoth.png",
		"biome": "beyond",
		"maxHp": 9999,
		"signatureCardId": "thecall",
		"cardsPerTurn": 3,
		"deck": ["eldersign", "star_sword", "yog_gun", "blood_toll", "tower_shield", "cthulhu_mail", "self_offering", "perfect_stealth", "deep_ones_blessing", "thecall", "silver_key", "collapse", "omnipotence", "transcendent"],
	},
	"treasure_wanderer": {
		"id": "treasure_wanderer",
		"name": "宝殻の徘徊者",
		"art": "res://art/pixel/treasure_wanderer.png",
		"poster": "res://art/pixel/treasure_wanderer.png",
		"biome": "reef",
		"maxHp": 18,
		"trait": "flee",
		"deck": ["buckler"],
	},
}

## enemies.ts getEnemy()
static func get_enemy(id: String) -> Dictionary:
	if not ENEMIES.has(id):
		push_error("Unknown enemy %s" % id)
		return {}
	return ENEMIES[id]


const BOSS_IDS := ["priest", "choir", "nurse", "flock", "herald", "warden", "bell", "nyar", "iha", "yog_sothoth"]


static func combat_ids_for_archetype(archetype: String) -> Array:
	var out: Array = []
	for enemy_id in ENEMIES.keys():
		if BOSS_IDS.has(enemy_id) or enemy_id == "treasure_wanderer":
			continue
		var def: Dictionary = ENEMIES[enemy_id]
		if str(def.get("archetype", "")) == archetype:
			out.append(enemy_id)
	return out

